<?php if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die();

class BookList extends CBitrixComponent
{
	public function executeComponent()
	{
		return parent::executeComponent(); // TODO: Change the autogenerated stub
	}

	public function fillArResult()
	{

	}
}
